version: '3'

services:

  parasoldb:
    image: mysql:5.7
    volumes:
    - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Gr33nAnaconda
      MYSQL_DATABASE: parasoldb
      MYSQL_USER: parasol
      MYSQL_PASSWORD: BlackCoff33
    ports:
      - 3306:3306

  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: pa55word
      MONGO_INITDB_DATABASE: parasoldb
      DATABASE_USERNAME: parasol
      DATABASE_PASSWORD: pa55word
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
    command: [--auth]

  parasol:
    build:
      context: ../server
    ports:
      - 8888:8888
    restart: unless-stopped
    environment: 
      #dev or H2 db and prod for MySQL
      SPRING_PROFILES_ACTIVE: prod,database/mysql      
    depends_on:
      - parasoldb  
      - mongo

  dataloader:
    build:
      context: ./dataloader
      dockerfile: Dockerfile
    command: dataloader.py
    volumes:
    - ./dataloader:/script/
    depends_on:
      - parasol
    restart: unless-stopped            
    

volumes:
  db_data: {}
  mongodb_data_container:  